import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import type { ApiInvoice } from "@/services/billing.service";

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

function fmtDate(iso: string): string {
  const d = new Date(iso);
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}

const STATUS_TEXT: Record<ApiInvoice["status"], { label: string; color: string }> = {
  PENDING: { label: "Due", color: "#b45309" },
  SUCCESS: { label: "Paid", color: "#16a34a" },
  FAILED: { label: "Failed", color: "#dc2626" },
  ABANDONED: { label: "Abandoned", color: "#6b7280" },
};

function invoiceHtml(invoice: ApiInvoice, familyName?: string): string {
  const status = STATUS_TEXT[invoice.status];
  const invoiceNo = invoice.id.slice(0, 8).toUpperCase();
  const amount = `${invoice.currency} ${invoice.amount.toLocaleString()}`;
  const period = `${fmtDate(invoice.billingPeriodStart)} – ${fmtDate(invoice.billingPeriodEnd)}`;
  const issued = fmtDate(invoice.createdAt);
  const paidRow = invoice.paidAt
    ? `<tr><td>Paid on</td><td style="text-align:right">${fmtDate(invoice.paidAt)}</td></tr>`
    : "";
  const refRow = invoice.reference
    ? `<tr><td>Reference</td><td style="text-align:right">${invoice.reference}</td></tr>`
    : "";

  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      * { font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; box-sizing: border-box; }
      body { margin: 0; padding: 40px; color: #111827; }
      .brand { font-size: 24px; font-weight: 800; color: #0f2461; }
      .brand span { color: #16a34a; }
      .sub { color: #6b7280; font-size: 12px; margin-top: 2px; }
      .title { font-size: 13px; letter-spacing: 2px; color: #9ca3af; margin-top: 36px; }
      .no { font-size: 20px; font-weight: 700; margin-top: 4px; }
      .pill { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px;
              font-weight: 700; color: ${status.color}; background: ${status.color}1a; margin-top: 10px; }
      table { width: 100%; border-collapse: collapse; margin-top: 28px; }
      td { padding: 12px 0; border-bottom: 1px solid #f3f4f6; font-size: 14px; color: #374151; }
      .total td { border-bottom: none; padding-top: 24px; }
      .total .amt { font-size: 26px; font-weight: 800; color: #0f2461; text-align: right; }
      .foot { margin-top: 48px; color: #9ca3af; font-size: 11px; line-height: 18px; }
    </style>
  </head>
  <body>
    <div class="brand">Supra<span>carer</span></div>
    <div class="sub">Clinically-coordinated homecare</div>

    <div class="title">INVOICE</div>
    <div class="no">#${invoiceNo}</div>
    <div class="pill">${status.label}</div>

    <table>
      ${familyName ? `<tr><td>Billed to</td><td style="text-align:right">${familyName}</td></tr>` : ""}
      <tr><td>Care period</td><td style="text-align:right">${period}</td></tr>
      <tr><td>Issued on</td><td style="text-align:right">${issued}</td></tr>
      ${paidRow}
      ${refRow}
      <tr class="total">
        <td style="font-weight:700;color:#111827">Total</td>
        <td class="amt">${amount}</td>
      </tr>
    </table>

    <div class="foot">
      Payments are processed securely by Paystack.<br />
      This invoice was generated by Supracarer. Thank you for trusting us with your care.
    </div>
  </body>
</html>`;
}

/**
 * Render an invoice to a PDF and open the share/save sheet.
 * Returns false if sharing isn't available on the device.
 */
export async function downloadInvoicePdf(
  invoice: ApiInvoice,
  familyName?: string,
): Promise<boolean> {
  const { uri } = await Print.printToFileAsync({
    html: invoiceHtml(invoice, familyName),
    base64: false,
  });
  if (!(await Sharing.isAvailableAsync())) return false;
  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    dialogTitle: `Invoice #${invoice.id.slice(0, 8).toUpperCase()}`,
    UTI: "com.adobe.pdf",
  });
  return true;
}
